name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for flagging your first issue. Pull requests are always welcome!'' first issue'
        pr-message: 'Thanks for opening your first pull request in this project! Questions or merge to come shortly 😄'' first pr'
